#!/usr/bin/env python3
##
## EPITECH PROJECT, 2020
## MUL_my_rpg_2019
## File description:
## create_enemy
##

file = open("resrc/item/item.txt", "a")
print("if type item is gun or knife, enter ammo and damage of the item")
type_i = input("type [char 32 max]: ")
name = input("name [char 32 max]: ")
if type_i == "gun" or type_i == "knife":
    damage = int(input("damage: "))
    ammo = int(input("ammo: "))
else:
    damage = 0
    ammo = 0
file.write("%s;%s;%d;%d\n" % (type_i, name, damage, ammo))
file.close()